// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/review/answer` のレスポンス。
 */
export type AnswerResponse = { interval_days: number, due_at: number, };
