// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/review/answer` のリクエスト。
 */
export type AnswerRequest = { stable_key: string, rating: "again" | "hard" | "good" | "easy", response?: string, };
