// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 学習日 1 日のレビュー件数。`day_start` は JST 04:00。
 */
export type DailyCount = { day_start: number, count: number, };
