// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ノート詳細のカード。未学習の定着率は null。
 */
export type DetailCard = { level: string, question: string, fsrs_state: string, due_at: number | null, retention: number | null, };
