// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MiddleStats } from "./MiddleStats";

export type MajorStats = { major: string, retention: number | null, card_count: number, middles: Array<MiddleStats>, };
