// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MinorStats } from "./MinorStats";

export type MiddleStats = { middle: string, retention: number | null, card_count: number, minors: Array<MinorStats>, };
