// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteStats } from "./NoteStats";

export type MinorStats = { minor: string, retention: number | null, card_count: number, notes: Array<NoteStats>, };
