// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewCard } from "./ReviewCard";

/**
 * `GET /api/review/next`。`card` が null なら今日の出題は終わり。
 */
export type NextResponse = { card: ReviewCard | null, };
