// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetailCard } from "./DetailCard";

/**
 * ノート 1 件のカード一覧。
 */
export type NoteDetail = { note_id: string, title: string, cards: Array<DetailCard>, };
