// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 出題するカード。
 */
export type ReviewCard = { stable_key: string, note_id: string, title: string, question: string, answer: string, level: string, };
