// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MajorStats } from "./MajorStats";

/**
 * 分類ツリー。各階層の定着率は、配下の対象カードの平均。
 */
export type Tree = { overall: number | null, majors: Array<MajorStats>, };
